apiVersion: v1
kind: Service
metadata:
  name: vllm-ray-head-lb
  namespace: vllm
spec:
  type: LoadBalancer
  selector:
    app: vllm-ray-head
  ports:
    - name: http
      port: 8000
      targetPort: 8000
